FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY publisher/pub.py pub.py
COPY mqtt.crt .
COPY mqtt.key .

CMD ["python", "pub.py"]
